GoogleElevation = 'http://maps.googleapis.com/maps/api/elevation/json?locations=$latitude,$longitude'
MusicBrainz = ''
OpenWeatherMap = 'http://api.openweathermap.org/data/2.5/weather?lat=$latitude&lon=$longitude'
GeoNamesFindNearby = 'http://api.geonames.org/findNearbyJSON?lat=$latitude&lng=$longitude&username=demo'
GeoNamesNeighbourhood = 'http://api.geonames.org/neighbourhoodJSON?lat=$latitude&lng=$longitude&username=demo'